name: Latest blog post workflow
on:
  schedule:
    # Runs every hour - did
    - cron: '15 14 1 * *'
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: 'https://blabley.org/category/news/feed/, https://dev.to/feed/rahuldkjain, https://medium.com/feed/@rahuldkjain'